// examples/Angular/src/app/todo-item/todoItem.component.ts
import { Component, inject,Input,ViewChild, AfterViewChecked,ElementRef  } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {Todo, TodosService } from '../todos.Service';
import { CommonModule } from '@angular/common'; 


@Component({
  standalone: true,
  imports:[FormsModule,CommonModule],
  selector: 'app-todo-todoItem',
  templateUrl: './todoItem.component.html',
})
export class todoItemComponent {
  private tosoService=inject(TodosService)
  edit=false
   @ViewChild('inputRef') inputRef!: ElementRef;

  
  @Input()
  todo!:Todo;
  

  ngAfterViewChecked() {

    if (this.edit && this.inputRef) {
      this.inputRef.nativeElement.focus();
    }
  }

  changeEdit(){
    
    if(this.inputRef.nativeElement.value!==''){
      this.todo.text=this.inputRef.nativeElement.value
    }
    this.edit=false
   

  }

  dbclick(){
    this.edit=true

  }
  

  toggleTodo(){
    this.todo.completed=!this.todo.completed
  }

  removeTodo(todo:Todo){
    this.tosoService.removeItem(todo)

  }

  
}

<li checked>
    <div class="todo-item" (dblclick)="dbclick()">

        <input *ngIf="edit" type="text" id="test_input" #inputRef (blur)="changeEdit()"  (keydown.enter)="changeEdit()"/>

        <input *ngIf="!edit" type="checkbox" [checked]="todo.completed" class="li_checkbox" (change)="toggleTodo()"/>
        <label *ngIf="!edit" class='check ' [ngClass]="todo.completed?'completed':''">
            {{todo.text}}
        </label>

        <button *ngIf="!edit" class="destroy" (click)="removeTodo(todo)">
            ✕
        </button>


    </div>
</li>

// examples/Vue/src/components/TodoItem.vue
<template>
  <li>
    <div class="todo-item" @dblclick="edit">
      <input
        v-if="editState"
        type="text"
        id="test_input"
        ref="editInput"
        v-model="newvalue"
        @keyup.enter="saveEdit"
        @blur="saveEdit"
      />
      <input
        @dblclick.stop
        v-if="!editState"
        :checked="todo.completed"
        type="checkbox"
        class="li_checkbox"
        @click="$emit('toggle-todo', todo)"
      />
      <label
        @dbclick.stop
        v-if="!editState"
        class="check"
        :class="todo.completed ? 'completed' : ''"
        >{{ todo.text }}</label
      >
      <button
        @dbclick.stop
        v-if="!editState"
        class="destroy"
        @click="$emit('destroy-todo', todo)"
      >
        ✕
      </button>
    </div>
  </li>
</template>

<script setup>
import { ref, nextTick } from "vue";
const editState = ref(false);
const editInput = ref(null);
const newvalue = ref("");
const emit = defineEmits(["toggle-todo", "destroy-todo", "edit-todo"]);

const edit = () => {
  newvalue.value = "";
  editState.value = true;
  nextTick(() => {
    editInput.value.focus();
  });
};

const saveEdit = () => {
  editState.value = false;
  if (newvalue.value.trim() !== "") {
    emit("edit-todo", props.todo, newvalue.value.trim());
  } else {
    newvalue.value = props.todo.text;
  }
};

const props = defineProps({ todo: Object });
</script>
