// examples/React/src/components/footer.tsx
import { useState } from "react"

type FooterProps={
    filterState?:string,
    todos:any[],
    setFilterState?:React.Dispatch<React.SetStateAction<string>>
    setTodos?:React.Dispatch<React.SetStateAction<any[]>>
}

export function Footer(props:FooterProps) {
    const number=props.todos.filter(item=>item.completed==false).length
    const stateList=['all','active','completed']
    const [currentState,setCurrent]=useState('all')
    

    const clearAll=()=>{
        props.setTodos&&props.setTodos(props.todos.filter(item=>item.completed==false))
    }
    

    return (
        <footer id="r_footer">
            <div id="state_bar" className="state_bar" >
                <span id="items_left">{number}件待办项</span>
                {stateList.map((item,index)=>(
                    <button key={index} className={`changeurl ${currentState==item?'active':''}`} onClick={()=>{
                        setCurrent(item)
                        props.setFilterState&&props.setFilterState(item)    
                    
                    }}>{item}</button>
                ))
                }
                <button id="clear_completed" onClick={clearAll}>清除所有完成项</button>
            </div >
        </footer >
    );
}

// examples/Angular/src/app/footer/footer.component.ts
import { Component,inject,EventEmitter, Output } from "@angular/core";
import { CommonModule } from '@angular/common'; 
import { Todo, TodosService} from "../todos.Service";


@Component({
    imports:[CommonModule],
    standalone:true,
    selector:'app-todo-footer',
    templateUrl:'./footer.component.html',
    

})

export class FooterComponent{

    private todoService=inject(TodosService)
    private defauleState:string='all'

    stateArr=['all','active','completed']

    @Output() State = new EventEmitter<string>();
    get todos(): Todo[]{
        const filter = 'all';
        return this.todoService.getItems(filter);
    }

    get current(): string{
        return this.defauleState
    }

    set current(state:string){
        this.defauleState=state

    }

    get length(): number{
        return this.todos.filter(item=>!item.completed).length
    }

    changeState=(state:string)=>{
       
        this.current=state
        this.State.emit(state)

    }

    removeAll(){
        this.todoService.clearCompleted()
    }



    
    
    
    

}
  <footer id="r_footer">
            <div id="state_bar" class="state_bar" >
                <span id="items_left">{{length}}件待办项</span>
                <button class="changeurl" [ngClass]="current==state?'active':''"  *ngFor="let state of stateArr; let i = index;" (click)="changeState(state)">{{state}}</button>
                <button id="clear_completed" (click)="removeAll()">清除所有完成项</button>
            </div >
        </footer >
